global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'messages-api'
    static_configs: 
      - targets: ['messages-api:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    
