{
 "title": "Messages API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of Messages Sent",
   "type": "stat",
   "description": "Total amount of messages sent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_messages_sent{job=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of Rooms Opened",
   "type": "stat",
   "description": "Total amount of rooms ever opened",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_rooms_opened{app=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current # of Rooms and HTTP Connections Open",
   "type": "timeseries",
   "description": "Amount of rooms and HTTP connections currently open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "current_rooms_open{job=\"messages-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "current_connections_open{job=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages API CPU Usage",
   "type": "timeseries",
   "description": "Graph showing the Docker container CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of Chat Messages Per Room ID",
   "type": "timeseries",
   "description": "Graph showing chat messages per chatroom ID",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "total_chat_messages_per_chatroom",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages API Memory Usage",
   "type": "timeseries",
   "description": "Graph showing the Docker container memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"messages-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}